import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

import { GithubIcon } from '@/components/icons/github-icon';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// #region RootLayout
// =============================================================================

const RootLayout: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='sticky top-0 z-10 h-10 w-full bg-white shadow-md'>
          <nav className='flex h-full w-full justify-between gap-6 px-4'>
            <div className='flex h-full items-center gap-4'>
              <Link className='text-lg tracking-widest' href='/'>
                QuickToolKit
              </Link>
            </div>
            <div className='flex h-full items-center gap-4'>
              <a
                href={process.env.NEXT_PUBLIC_GITHUB_REPO_URL ?? ''}
                target='_blank'
                rel='noopener noreferrer'
              >
                <GithubIcon size={24} />
              </a>
            </div>
          </nav>
        </header>
        <main className='flex w-full items-center justify-center'>
          {children}
        </main>
      </body>
    </html>
  );
};

// #region Exports
// =============================================================================

export default RootLayout;
