import { createHash } from 'node:crypto';
import fs, { readFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT_DIR = path.resolve(import.meta.dirname, '..');
const SCRIPT_NAME = path.basename(import.meta.filename);

const VIPS_BASE_PATH = 'vips';
const VIPS_LIB_FOLDER = path.join(ROOT_DIR, 'node_modules', 'wasm-vips', 'lib');
const VIPS_PUBLIC_FOLDER = path.join(ROOT_DIR, 'public', VIPS_BASE_PATH);
const VIPS_GENERATED_FILE_PATH = path.join(
  ROOT_DIR,
  'src',
  'lib',
  'vips',
  '__generated__.ts',
);

async function setupVips() {
  await fs.rm(VIPS_PUBLIC_FOLDER, { recursive: true, force: true });
  console.info(`✅ Removed directory: ${VIPS_PUBLIC_FOLDER}`);

  const files = await Array.fromAsync(
    fs.glob([
      path.join(VIPS_LIB_FOLDER, '*.js'),
      path.join(VIPS_LIB_FOLDER, '*.wasm'),
    ]),
  );

  // Compute a hash of all the files to include in the directory
  // This is so we can set the Cache-Control headers to never expire the files
  // If any file content or name changes, there will be a new path.
  const hash = createHash('sha256');
  for (const file of files) {
    const data = await readFile(file);
    hash.update(path.basename(file));
    hash.update(data);
  }
  const hashHex = hash.digest('hex').slice(0, 16);
  const destFolder = path.join(VIPS_PUBLIC_FOLDER, hashHex);

  await fs.mkdir(destFolder, { recursive: true });
  console.info(`✅ Created directory: ${destFolder}`);

  // Copy the files over to the destination
  for (const file of files) {
    const filename = path.basename(file);
    const target = path.join(destFolder, filename);
    await fs.copyFile(file, target);
  }
  console.info(`✅ Copied vips files to: ${destFolder}`);

  // Create the __generated__.ts file with mappings
  const generatedFileContent = [
    `// Generated by ${SCRIPT_NAME}`,
    '',
    `export const PUBLIC_VIPS_PATH = '/vips/${hashHex}/vips-es6.js';`,
    '',
    `export const PUBLIC_VIPS_PATH_NODE = '/vips/${hashHex}/vips-node.js';`,
    '',
  ].join('\n');
  await fs.writeFile(VIPS_GENERATED_FILE_PATH, generatedFileContent);
  console.info(`✅ Updated file: ${VIPS_GENERATED_FILE_PATH}`);
}

void setupVips();
